name: Build and Push WeasyPrint Image

on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/build-push-weasyprint.yml
    - app/**
    - requirements.txt
    - Dockerfile
    - .dockerignore

env:
  GITHUB_REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-push-weasyprint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: read
      packages: write

    steps:
    - uses: hmarr/debug-action@f7318c783045ac39ed9bb497e22ce835fdafbfe6
    - uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08

    - name: Build and Push
      uses: egose/actions/docker-build-push@39eedd7f68a65004b0f9e8872feb494900257dba
      with:
        registry-url: ${{ env.GITHUB_REGISTRY }}
        registry-username: ${{ github.actor }}
        registry-password: ${{ secrets.GITHUB_TOKEN }}
        image-name: bcgov/weasyprint
        docker-context: .
        docker-file: Dockerfile
        metadata-tags: |
          type=raw,value=latest
          type=sha,format=long,prefix=,suffix=
